
----
AUTOR:	ALONSO MORALES SALAZAR
SP:		INSERTA REGISTRO CATEGORIA
--
CREATE PROCEDURE VT_CATEGORIA_INSERT
@CODCAT	CHAR(2),
@DESCAT VARCHAR(30)
AS
INSERT INTO TB_CATEGORIA
	(COD_CAT,DES_CAT)
	VALUES(@CODCAT,@DESCAT)

=======================================================================
/*
AUTOR:	ALONSO MORALES SALAZAR
SP:		ACTUALIZA REGISTRO CATEGORIA
*/
CREATE PROCEDURE VT_CATEGORIA_UPDATE
@CODCAT	CHAR(2),
@DESCAT VARCHAR(30)
AS
UPDATE TB_CATEGORIA
	SET DES_CAT=@DESCAT
	WHERE COD_CAT=@CODCAT
	
=======================================================================
/*
AUTOR:	ALONSO MORALES SALAZAR
SP:		ELIMINA	 REGISTRO CATEGORIA
*/
CREATE PROCEDURE VT_CATEGORIA_DELETE
@CODCAT	CHAR(2)
AS
SET NOCOUNT ON

DELETE TB_CATEGORIA WHERE COD_CAT=@CODCAT


=======================================================================
/*
AUTOR:	ALONSO MORALES SALAZAR
SP:		MUESTRA LOS REGISTROS DE CATEGORIA
*/
CREATE PROCEDURE VT_CATEGORIA_GET01
@CODCAT VARCHAR(2)
AS
SELECT COD_CAT,DES_CAT FROM TB_CATEGORIA
WHERE COD_CAT=@CODCAT

=======================================================================
/*
AUTOR:	ALONSO MORALES SALAZAR
SP:		MUESTRA LOS REGISTROS DE CATEGORIA
*/
CREATE PROCEDURE VT_CATEGORIA_GET02
AS
SET NOCOUNT ON

SELECT COD_CAT,DES_CAT FROM TB_CATEGORIA
=======================================================================

/*
AUTOR:	ALONSO MORALES SALAZAR
SP:		MUESTRA LOS REGISTROS DE CATEGORIA X COINCIDENCIAS
*/
CREATE PROCEDURE VT_CATEGORIA_GET03
@criterio VARCHAR(50)
AS
SELECT COD_CAT,DES_CAT FROM TB_CATEGORIA
WHERE DES_CAT LIKE '%'+@criterio+'%'
